"""Pydantic v2 schemas — REST responses and WebSocket protocol envelopes."""
from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# Message types
# ─────────────────────────────────────────────────────────────────────────────

class MessageType(str, Enum):
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    SYSTEM = "SYSTEM"


# ─────────────────────────────────────────────────────────────────────────────
# Sender profile embedded in message responses
# ─────────────────────────────────────────────────────────────────────────────

class SenderInfo(BaseModel):
    id: uuid.UUID
    username: str
    display_name: str
    avatar_url: Optional[str] = None

    model_config = {"from_attributes": True}


# ─────────────────────────────────────────────────────────────────────────────
# REST schemas
# ─────────────────────────────────────────────────────────────────────────────

class ChatMessageResponse(BaseModel):
    id: uuid.UUID
    community_id: uuid.UUID
    sender: SenderInfo
    client_message_id: uuid.UUID
    message_type: MessageType
    content: Optional[str]
    reply_to_message_id: Optional[uuid.UUID]
    created_at: datetime
    edited_at: Optional[datetime]
    is_deleted: bool

    model_config = {"from_attributes": True}


class ChatHistoryResponse(BaseModel):
    """Cursor-paginated chat history (newest-first)."""
    items: List[ChatMessageResponse]
    next_cursor: Optional[str]   # opaque base64-encoded cursor
    has_more: bool


class WsTicketResponse(BaseModel):
    """Short-lived one-time WS connection ticket."""
    ticket: str
    expires_in_seconds: int


class PresenceResponse(BaseModel):
    """Online member IDs for a community chat."""
    community_id: uuid.UUID
    online_user_ids: List[str]
    online_count: int


# ─────────────────────────────────────────────────────────────────────────────
# WebSocket Application Protocol
# ─────────────────────────────────────────────────────────────────────────────

class WsEventType(str, Enum):
    # Client → Server
    MESSAGE_SEND = "message.send"
    TYPING_START = "typing.start"
    TYPING_STOP = "typing.stop"
    HEARTBEAT = "heartbeat"

    # Server → Client
    MESSAGE_CREATED = "message.created"
    MESSAGE_UPDATED = "message.updated"
    MESSAGE_DELETED = "message.deleted"
    PRESENCE_JOINED = "presence.joined"
    PRESENCE_LEFT = "presence.left"
    MEMBERSHIP_REVOKED = "membership.revoked"
    ERROR = "error"
    ACK = "ack"


class WsMessageSendPayload(BaseModel):
    content: str = Field(..., max_length=4000)
    reply_to_message_id: Optional[uuid.UUID] = None
    client_message_id: uuid.UUID  # generated by client for idempotency


class WsIncoming(BaseModel):
    """Envelope for every message received from a WebSocket client."""
    type: WsEventType
    request_id: Optional[str] = None   # echoed back in ACK
    payload: Optional[Dict[str, Any]] = None


class WsOutgoing(BaseModel):
    """Envelope for every message sent to a WebSocket client."""
    type: WsEventType
    request_id: Optional[str] = None
    payload: Optional[Dict[str, Any]] = None

    def to_json(self) -> str:
        return self.model_dump_json()
